export const envs = {
  TOKEN_FACTORY_ADDRESS:
    process.env.NEXT_PUBLIC_PUMP_CONTRACT_ADDRESS_ARBITRUM!,
  USDT_ADDRESS: process.env.NEXT_PUBLIC_USDT_ADDRESS_ARBITRUM!,
  SCAN_URL: process.env.NEXT_PUBLIC_ARBITRUM_SCAN_URL!,
  CONTRACT_ROUTER_ADDRESS: process.env.NEXT_PUBLIC_CONTRACT_ROUTER!,
};
